# ./config.yaml
# -*- coding: GBK -*-

## MySQL database basic settings
## *hostname(IP), serving port, username, password
database:
  host: localhost
  port: 3306
  username: root
  password: 123456

## All departments and database name lists
departments:
  DeptA: ['a1', 'a2', 'a3']
  DeptB: ['b']
  DeptC: ['c1', 'c2']

## Column IDs and each column's display name and width
## Categorized by the first column by default
## *Modifications may cause early terminals record files to unable to open
columns:
  '#0':       # Necessary, do not change column ID
    fullname: 'Department'
    width: 140
  name:       # Unnecessary, column ID matchs SELECT names below
    fullname: 'Name'
    width: 180
  type:       # Unnecessary, do not change column ID
    fullname: 'Type'
    width: 120
  ip:         # Unnecessary, column ID matchs SELECT names below
    fullname: 'IP Address'
    width: 100
  latency:    # Necessary, do not change column ID
    fullname: 'Latency'
    width: 100

## 'type'(terminal's type) and SQL SELECT code for each types
## *Needs 'name'(terminal's name) and 'ip'(terminal's IP)£¬match column IDs
dumpcodes:
  TypeX: "SELECT name, ip FROM tablex"
  TypeY: "SELECT devicename 'name', ip FROM devicetable, iptable WHERE devicetable.deviceid = iptable.deviceid"
